# Default values for hpe-csi-driver Helm chart
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# Control CSP Service and Deployments for HPE storage products
disable:
  nimble: false
  primera: false
  alletra6000: false
  alletra9000: false
  alletraStorageMP: false

# For controlling automatic iscsi/multipath package installation
disableNodeConformance: false

# For controlling automatic iscsi/multipath service configuration
disableNodeConfiguration: false

# imagePullPolicy applied for all hpe-csi-driver images
imagePullPolicy: "IfNotPresent"

# Cluster wide values for CHAP authentication
iscsi:
  chapUser: ""
  chapPassword: ""

# Log level for all hpe-csi-driver components
logLevel: "info"

# Kubelet root directory path
kubeletRootDir: "/var/lib/kubelet/"

# NodeGetVolumestats will be called by default, set true to disable the call 
disableNodeGetVolumeStats: false

controller:

  # These values map directly to yaml in the deployment spec, see the kubernetes docs for info
  labels: {}

  # These values map directly to yaml in the deployment spec, see the kubernetes docs for info
  nodeSelector: {}

  # These values map directly to yaml in the deployment spec, see the kubernetes docs for info
  tolerations: []

  affinity: {}

csp:

  # These values map directly to yaml in the deployment spec, see the kubernetes docs for info
  labels: {}

  # These values map directly to yaml in the deployment spec, see the kubernetes docs for info
  nodeSelector: {}

  # These values map directly to yaml in the deployment spec, see the kubernetes docs for info
  tolerations: []

  affinity: {}

node:

  # These values map directly to yaml in the deployment spec, see the kubernetes docs for info
  labels: {}

  # These values map directly to yaml in the deployment spec, see the kubernetes docs for info
  nodeSelector: {}

  # These values map directly to yaml in the deployment spec, see the kubernetes docs for info
  tolerations: []

  affinity: {}

# Release images
images:
  csiNodeDriver: quay.io/hpestorage/csi-driver:v2.4.2
  csiControllerDriver: quay.io/hpestorage/csi-driver:v2.4.2
  nimbleCSP: quay.io/hpestorage/alletra-6000-and-nimble-csp:v2.4.1
  primera3parCSP: quay.io/hpestorage/alletra-9000-primera-and-3par-csp:v2.4.2
  nfsProvisioner: quay.io/hpestorage/nfs-provisioner:v3.0.4
  csiExtensions: quay.io/hpestorage/csi-extensions:v1.2.6
  csiVolumeGroupProvisioner: quay.io/hpestorage/volume-group-provisioner:v1.0.5
  csiVolumeGroupSnapshotter: quay.io/hpestorage/volume-group-snapshotter:v1.0.5
  csiVolumeMutator: quay.io/hpestorage/volume-mutator:v1.3.5
  csiAttacher: registry.k8s.io/sig-storage/csi-attacher:v4.5.0
  csiNodeDriverRegistrar: registry.k8s.io/sig-storage/csi-node-driver-registrar:v2.10.0
  csiProvisioner: registry.k8s.io/sig-storage/csi-provisioner:v4.0.0
  csiResizer: registry.k8s.io/sig-storage/csi-resizer:v1.9.3
  csiSnapshotter: registry.k8s.io/sig-storage/csi-snapshotter:v6.3.3
